### ISSUE TITLE
Something about DAG

### ISSUE THREAD

**Issue by sandervdorth** [raidendotai/cofounder#10]
While installing its giving me below 'error'. Now the dashboard doesnt seem to work correctly.

build:DAG : parent node WEBAPP:STORE::GENERATE of node WEBAPP:ROOT::GENERATE not found in DAG - skipping dependency

**Comment by rahmat-ullah** [comment]
build:DAG : parent node WEBAPP:STORE::GENERATE of node WEBAPP:ROOT::GENERATE not found in DAG - skipping dependency

I got the same.

**Comment by raidendotai** [comment]
likely debugging leftovers
will check - thanks
