### ISSUE TITLE
error when trying to launch

### ISSUE THREAD

**Issue by appbomb** [raidendotai/cofounder#16]
> wrote ./cofounder/api/.env

added 363 packages, and audited 364 packages in 5s

63 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (4 moderate, 1 critical)

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

> start
> nodemon --loader esm-module-alias/loader --no-warnings server.js

sh: nodemon: command not found
Error: Command failed: npm i && npm run start
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at main (file:///Users/banger/.npm/_npx/f748a024b9cdb317/node_modules/@openinterface/cofounder/bin.js:130:5) {
  status: 127,
  signal: null,
  output: [ null, null, null ],
  pid: 87732,
  stdout: null,
  stderr: null
}
banger@BANGERs-MacBook-Air cofounder %

**Comment by LLMFocus** [comment]
go to \cofounder\api
npm run start

**Comment by appbomb** [comment]
npm error code ENOENT
npm error syscall open
npm error path /Users/banger/cofounder/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file
or directory, open '/Users/banger/cofounder/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent

0 verbose cli /opt/homebrew/Cellar/node/22.9.0_1/bin/node
/opt/homebrew/bin/npm
1 info using ***@***.***
2 info using ***@***.***
3 silly config load:file:/opt/homebrew/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/banger/cofounder/.npmrc
5 silly config load:file:/Users/banger/.npmrc
6 silly config load:file:/opt/homebrew/etc/npmrc
7 verbose title npm run start
8 verbose argv "run" "start"
9 verbose logfile logs-max:10
dir:/Users/banger/.npm/_logs/2024-11-01T16_03_49_533Z-
10 verbose logfile
/Users/banger/.npm/_logs/2024-11-01T16_03_49_533Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
12 verbose stack Error: Could not read package.json: Error: ENOENT: no such
file or directory, open '/Users/banger/cofounder/package.json'
12 verbose stack     at async open (node:internal/fs/promises:638:25)
12 verbose stack     at async readFile (node:internal/fs/promises:1238:14)
12 verbose stack     at async read
***@***.***/package-json/lib/read-package.js:9:18)
12 verbose stack     at async PackageJson.load
***@***.***/package-json/lib/index.js:130:31)
12 verbose stack     at async PackageJson.normalize
***@***.***/package-json/lib/index.js:116:5)
12 verbose stack     at async #run
(/opt/homebrew/lib/node_modules/npm/lib/commands/run-script.js:85:13)
12 verbose stack     at async RunScript.exec
(/opt/homebrew/lib/node_modules/npm/lib/commands/run-script.js:39:7)
12 verbose stack     at async Npm.exec
(/opt/homebrew/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports
(/opt/homebrew/lib/node_modules/npm/lib/cli/entry.js:74:5)
13 error code ENOENT
14 error syscall open
15 error path /Users/banger/cofounder/package.json
16 error errno -2
17 error enoent Could not read package.json: Error: ENOENT: no such file or
directory, open '/Users/banger/cofounder/package.json'
18 error enoent This is related to npm not being able to find a file.
18 error enoent
19 verbose cwd /Users/banger/cofounder
20 verbose os Darwin 22.3.0
21 verbose node v22.9.0
22 verbose npm  v10.8.3
23 verbose exit -2
24 verbose code -2
25 error A complete log of this run can be found in:
/Users/banger/.npm/_logs/2024-11-01T16_03_49_533Z-debug-0.log




пт, 1 нояб. 2024 г. в 16:17, LLMFocus ***@***.***>:

**Comment by Wakiki93** [comment]
I don't wanna sound like a dummy but I was in the same boat. Use gpt to debug it. That's how I got mine working

**Comment by tachun** [comment]
I resolve this by Installing 'nodemon' globally `npm install -g nodemon`.
