### ISSUE TITLE
SYSTEM_RUN_ERR -- image exceeds 5 MB maximum

### ISSUE THREAD

**Issue by lukemcc20** [raidendotai/cofounder#17]
I currently have this error and just wondering if anyone has a workaround or a way to troubleshoot the error.

TIA

**Error code** 

{
  SYSTEM_RUN_ERR: {
    err: Error: Error: 400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.0.content.1.image.source.base64: image exceeds 5 MB maximum: 6279864 bytes > 5242880 bytes"}}
        at .../cofounder/api/build.js:107:17
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async .../cofounder/api/build.js:84:25
        at async .../cofounder/api/node_modules/p-queue/dist/index.js:187:36,
    id: 'op:LLM::GEN'
  }
}

**Comment by radrad** [comment]
I have the same error in addition to reaching Claude error
          type: 'rate_limit_error',
          message: 'Number of request tokens has exceeded your daily rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales 
to discuss your options for a rate limit increase.'
        }

**Comment by raidendotai** [comment]
yes - issue was api serving back files bigger than claude limit
serverside fix otw
