### ISSUE TITLE
Error `generated is empty` even after response is coming.

### ISSUE THREAD

**Issue by rahulgurujala** [raidendotai/cofounder#2]
I can see generation and streaming in nodes, but suddenly it stops and gives me the following error. I wait for multiple retries but it still same issue. I assume Tokens are getting exhausted and the code is not handling this. Any fix for it? 

```
name":"Backend code","desc"
{
  asyncretry_error: {
    id: 'BACKEND:SERVER::GENERATE',
    error: Error: backend:server:generate error - generated is empty
        at Object.backendServerGenerate [as BACKEND:SERVER::GENERATE] (./cofounder/api/system/functions/backend/server.js:314:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async ./cofounder/api/build.js:87:30
        at async ./cofounder/api/build.js:84:25
        at async ./cofounder/api/node_modules/p-queue/dist/index.js:187:36
  }
}
log:complete: node:op:LLM::GEN  {"context":{"streams":{},"project":"myproject","sequence":{"resume":8},"operation":{"key":"backend.server.main","meta":{"name":"Backend code","desc"
{
  asyncretry_error: {
    id: 'BACKEND:SERVER::GENERATE',
    error: Error: backend:server:generate error - generated is empty
        at Object.backendServerGenerate [as BACKEND:SERVER::GENERATE] (./cofounder/api/system/functions/backend/server.js:314:9)
        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
        at async ./cofounder/api/build.js:87:30
        at async ./cofounder/api/build.js:84:25
        at async ./cofounder/api/node_modules/p-queue/dist/index.js:187:36
  }
}
```

**Comment by raidendotai** [comment]
that code snippet handles exactly that and is already implement ,
namely retries with backoff in cases like
- llm api problems ( rate limited , api cant be reached , ... )
- instructions not followed by llm ( ie. empty code )
- llm output not maching structure ( ie. code not written inside block )

you're most likely hitting output tokens limit of the model in your specific case,
and it doesnt get to finish generating code

fix would be using model with higher output tokens

i'll use o1-mini with 32k as default in a lot of cases on next update, should fix most ^

in the meantime , you can try digging into `cofounder/api/system/functions/backend/server.js` and specify desired models (same approach for any other inference pass)
(also make sure `cofounder/api/.env` sets openai for LLMs , else everything defaults to `claude 3.5 sonnet` )
