### ISSUE TITLE
OpenAI API not being used

### ISSUE THREAD

**Issue by BioCruz-sudo** [raidendotai/cofounder#50]
I've been getting consistent anthropic API rate limits after a single prompt that uses all my daily tokens since I'm still tier 1, however I put 20$ on my OpenAI API for gpt4o and I noticed that my usage hasn't gone up and I only used 0.01$ for OpenAI. However, I look at claude/anthropic and it's been BURNING all of my credits. I'm not sure if the Anthropic API rate limit error is a glitch and building the app is actually using claude. So far building this one app (still half-way due to rate limits) has cost me 22$ in API credits which I find ridiculous and seems like I'm getting charged for an API call just to receive the rate limit error. Anyone else getting this issue?

**Comment by hiddenhidden** [comment]
I'm encountering the same issue with Anthropic's API rate limits. Despite having a minimal usage with OpenAI (only $0.01 so far), I've hit my daily token limit with Anthropic after only a few interactions, which has effectively halted my work with Cofounder. I’ve reached out to Anthropic’s sales team, but I think there’s an opportunity here to improve API usage within Cofounder itself.

Would it be possible to add an option to balance API usage between Anthropic and OpenAI? Perhaps you could prioritize OpenAI for tasks like embeddings and reserve Anthropic for specific inference cases where Claude might offer advantages. This would allow users to make the most of both platforms’ quotas and avoid hitting rate limits so quickly on Anthropic.

A feature where users could set preferences or priorities for different LLM providers might make Cofounder more flexible and accessible, especially for those on lower API tiers. I will post here if I hear back from Anthropic Sales.

Thanks -
