### ISSUE TITLE
Rate limits handling

### ISSUE THREAD

**Issue by dorianbodnariuc** [raidendotai/cofounder#83]
Is there a way to handle LLM provider rate limiting? 
'anthropic-ratelimit-requests-limit': '1000',
        'anthropic-ratelimit-requests-remaining': '999',
        'anthropic-ratelimit-requests-reset': '2024-11-12T04:41:27Z',
        'anthropic-ratelimit-tokens-limit': '2500000',
        'anthropic-ratelimit-tokens-remaining': '0',
        'anthropic-ratelimit-tokens-reset': '2024-11-13T04:48:07Z',

The script keeps trying Anthropic but Anthropic responds that they blocked the access for 24 hours. So it's going to be 24 hours of wasted energy. 
I think there might be a problem with saving the project, because I lost a project when I accidentally closed my browser. 
If there is a way of saving projects, or just pause them, can you please point me to the documentation?

**Comment by hongthana** [comment]
Refer to this [issue](https://github.com/raidendotai/cofounder/issues/2#issuecomment-2393757090)

**Comment by dorianbodnariuc** [comment]
Thank you @hongthana
